name: Build and Release TextSweeper Artifacts

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: Grimakis/m100-release-workflow/.github/workflows/release.yml@v1
    with:
      source: src/TSWEEP.DO
      ascii-name: TSWEEP.DO
      tokenized-name: TSWEEP.BA
      version-var: "VE$"
    secrets: inherit
